@startuml
title Use case diagram
left to right direction
skinparam packageStyle rect
actor User
actor Interlocutor
actor Fitness_Tracker
actor Service_EPay
actor API_Music_Recomendation
actor API_Fitness_Recomendation
rectangle Software {
  User -- (Authorisation/Registration)
  Interlocutor -- (Authorisation/Registration)
  Fitness_Tracker -- (Connect tracking)
  Service_EPay -- (Pay the subscription)
  API_Music_Recomendation -- (View music recommendations)
  API_Fitness_Recomendation -- (View progress on physical training)
  Interlocutor --|> User

  (Connect tracking) <.. (View data from a smart watch/fitness tracker) : <<include>>
  (Authorisation/Registration) <.. (Connect tracking) : <<include>>
  (Authorisation/Registration) <.. (Entering physical health goals) : <<include>>
  (Authorisation/Registration) <.. (View progress on physical training) : <<include>>
  (Authorisation/Registration) <.. (View music recommendations) : <<include>>
  (Authorisation/Registration) <.. (View fitness recommendations) : <<include>>
  (Authorisation/Registration) <.. (Pay the subscription) : <<include>>
}
@enduml
