name: JsonSchemaLinter
on:
 push:
  branches: Lab11
jobs:
 json_linter_test:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: "actions/checkout@v3"
  - name: Executive
    run: |
      npm i -g @prantlf/jsonlint
      jsonlint $GITHUB_WORKSPACE/DataSchema.json
