name: ProgramCode
on: push:
    branches: Lab11
jobs:
  ProgramCode:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ProgramCode
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVASCRIPT_STANDART: true
          FILTER_REGEX_INCLUDE: ./*.js$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
